apiVersion: v1
kind: ServiceAccount
metadata:
  name: honeypod-manager
  namespace: honeypod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeypod-controller-manager
  namespace: honeypod
  labels:
    app.kubernetes.io/name: honeypod-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: honeypod-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: honeypod-operator
    spec:
      serviceAccountName: honeypod-manager
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
      - name: manager
        image: honeypod/manager:latest
        imagePullPolicy: IfNotPresent
        command: ["/manager"]
        ports:
        - name: metrics
          containerPort: 8080
        - name: health
          containerPort: 8081
        - name: audit-webhook
          containerPort: 9880
        - name: join-webhook
          containerPort: 9443
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
